// elementData.js
const elementData = [
  { symbol: "H",  name: "수소",      atomicNumber: 1 ,atomicWeight: 39.0983, hasSpectrumData: true },
  { symbol: "He", name: "헬륨",      atomicNumber: 2, atomicWeight: null, hasSpectrumData: false  },
  { symbol: "Li", name: "리튬",      atomicNumber: 3 },
  { symbol: "Be", name: "베릴륨",    atomicNumber: 4 },
  { symbol: "B",  name: "붕소",      atomicNumber: 5 },
  { symbol: "C",  name: "탄소",      atomicNumber: 6 },
  { symbol: "N",  name: "질소",      atomicNumber: 7 },
  { symbol: "O",  name: "산소",      atomicNumber: 8 },
  { symbol: "F",  name: "플루오린",  atomicNumber: 9 },
  { symbol: "Ne", name: "네온",      atomicNumber: 10 },
  { symbol: "Na", name: "나트륨",    atomicNumber: 11 },
  { symbol: "Mg", name: "마그네슘",  atomicNumber: 12 },
  { symbol: "Al", name: "알루미늄",  atomicNumber: 13 },
  { symbol: "Si", name: "규소",      atomicNumber: 14 },
  { symbol: "P",  name: "인",        atomicNumber: 15 },
  { symbol: "S",  name: "황",        atomicNumber: 16 },
  { symbol: "Cl", name: "염소",      atomicNumber: 17 },
  { symbol: "Ar", name: "아르곤",    atomicNumber: 18 },
  {
    "elementId": 19,
    "symbol": "K",
    "name": "칼륨",
    "atomicWeight": 39.0983,
    "hasSpectrumData": true,
    "energyLevels": "2 8 8 1",
    "electronegativity": 0.82,
    "meltingPoint": 63.38,
    "boilingPoint": 758.85,
    "radius": 243,
    "discover": "AD 1807",
    "state": "고체",
    "ionizationEnergies": [ // 에너지 값이 없으면 리스트가 비어있음, 1번째 이온화 에너지 -> 0번째 인덱스
        418.8,
        3052.0,
        4420.0,
        5877.0,
        7975.0,
        9590.0,
        11343.0,
        14944.0,
        16963.7,
        48610.0,
        54490.0,
        60730.0,
        68950.0,
        75900.0,
        83080.0,
        93400.0,
        99710.0,
        444880.0,
        476063.0
    ]
  },
  { symbol: "Ca", name: "칼슘",      atomicNumber: 20 },
  { symbol: "Lr", name: "로렌슘",      atomicNumber: 118 },
];

export default elementData;
